version: "3.9"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./mongodb:/data/db
    ports:
      - "27017:27017"
    restart: "unless-stopped"
  serverexample:
    build:
      context: .
      dockerfile: Dockerfile
    image: serverexample
    container_name: server
    volumes:
      - ./core/target/web:/web
    ports:
      - "5050:5050"
    restart: "no"
